#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source .zsh_wsl

# Source .zsh_aliases
if [[ -s "${ZDOTDIR:-$HOME}/.zsh_aliases" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh_aliases"
fi

path+="$HOME/.local/bin"

# Customize to your needs...
