#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source .zsh_wsl

# Aliases
alias gigls='git ls-files -io --exclude-from=.gitignore'
alias gigrm='git ls-files -io --exclude-from=.gitignore | xargs -d \\n rm -rf'

# Functions

# Path
path+="$HOME/.local/bin"

# Customize to your needs...
